=== asyncapi/spec-json-schemas/definitions/3.0.0/asyncapi.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://asyncapi.com/definitions/3.0.0/asyncapi.json",
  "title": "AsyncAPI 3.0.0 schema.",
  "type": "object",
  "required": [
    "asyncapi",
    "info"
  ],
  "properties": {
    "id": {
      "description": "A unique id representing the application.",
      "type": "string",
      "format": "uri"
    },
    "asyncapi": {
      "description": "The AsyncAPI specification version of this document.",
      "type": "string",
      "const": "3.0.0"
    },
    "channels": {
      "$ref": "http://asyncapi.com/definitions/3.0.0/channels.json"
    },
    "components": {
      "$ref": "http://asyncapi.com/definitions/3.0.0/components.json"
    },
    "defaultContentType": {
      "description": "Default content type to use when encoding/decoding a message's payload.",
      "type": "string"
    },
    "info": {
      "$ref": "http://asyncapi.com/definitions/3.0.0/info.json"
    },
    "operations": {
      "$ref": "http://asyncapi.com/definitions/3.0.0/operations.json"
    },
    "servers": {
      "$ref": "http://asyncapi.com/definitions/3.0.0/servers.json"
    }
  },
  "patternProperties": {
    "^x-[\\w\\d\\.\\x2d_]+$": {
      "$ref": "http://asyncapi.com/definitions/3.0.0/specificationExtension.json"
    }
  },
  "additionalProperties": false
}

=== asyncapi/spec-json-schemas/test/docs/3.0.0/streetlights-asyncapi.json
{
  "asyncapi": "3.0.0",
  "info": {
    "title": "Account Service",
    "version": "1.0.0",
    "description": "This service is in charge of processing user signups"
  },
  "channels": {
    "AsyncAPI-UserSignedUpChannel": {
      "address": "user/signedup/{test_param}",
      "parameters": {
        "test_param": {
          "enum": [
            "test"
          ],
          "default": "test",
          "description": "Just a test description",
          "examples": [
            "test"
          ],
          "location": "$message.payload#",
          "x-custom-extension": "test"
        }
      },
      "messages": {
        "AsyncAPI-UserSignedUp": {
          "$ref": "#/components/messages/AsyncAPI-UserSignedUp"
        }
      }
    }
  },
  "operations": {
    "AsyncAPI-PublishUserSignedUp": {
      "action": "send",
      "channel": {
        "$ref": "#/channels/AsyncAPI-UserSignedUpChannel"
      },
      "bindings": {
        "mqtt": {
          "bindingVersion": "0.2.0",
          "qos": 1
        },
        "kafka": {
          "bindingVersion": "0.3.0",
          "clientId": {
            "type": "string",
            "enum": [
              "my-app-id"
            ]
          }
        }
      }
    },
    "AsyncAPI-PublishUserSignedUpDefaultBinding": {
      "action": "send",
      "channel": {
        "$ref": "#/channels/AsyncAPI-UserSignedUpChannel"
      },
      "bindings": {
        "mqtt": {
          "qos": 1
        },
        "kafka": {
          "clientId": {
            "type": "string",
            "enum": [
              "my-app-id"
            ]
          }
        }
      }
    }
  },
  "components": {
    "messages": {
      "AsyncAPI-UserSignedUp": {
        "payload": {
          "schemaFormat": "application/vnd.aai.asyncapi+json;version=3.0.0",
          "schema": {
            "type": "object",
            "properties": {
              "displayName": {
                "type": "string",
                "description": "Name of the user"
              },
              "email": {
                "type": "string",
                "format": "email",
                "description": "Email of the user"
              }
            },
            "externalDocs": {
              "url": "https://account-service/docs/UserSignedUp"
            },
            "deprecated": false
          }
        }
      },
      "AsyncAPI-UserSignedUpV2": {
        "payload": {
          "type": "object",
          "properties": {
            "displayName": {
              "type": "string",
              "description": "Name of the user"
            },
            "email": {
              "type": "string",
              "format": "email",
              "description": "Email of the user"
            }
          },
          "externalDocs": {
            "url": "https://account-service/docs/UserSignedUp"
          },
          "deprecated": false
        }
      },
      "AsyncAPI-UserSignedUpV3": {
        "payload": {
          "$ref": "external-schema.json"
        }
      }
    }
  }
}

=== asyncapi/spec-json-schemas/test/docs/3.0.0/streetlights-unknown.json
{
  "asyncapi": "3.0.0",
  "info": {
    "title": "Account Service",
    "version": "1.0.0",
    "description": "This service is in charge of processing user signups"
  },
  "channels": {
    "Unknown-UserSignedUpChannel": {
      "address": "user/signedup/{test_param}",
      "parameters": {
        "test_param": {
          "enum": [
            "test"
          ],
          "default": "test",
          "description": "Just a test description",
          "examples": [
            "test"
          ],
          "location": "$message.payload#",
          "x-custom-extension": "test"
        }
      },
      "messages": {
        "UserSignedUp": {
          "$ref": "#/components/messages/Unknown-UserSignedUp"
        }
      }
    }
  },
  "operations": {
    "Unknown-PublishUserSignedUp": {
      "action": "send",
      "channel": {
        "$ref": "#/channels/Unknown-UserSignedUpChannel"
      },
      "bindings": {
        "mqtt": {
          "bindingVersion": "0.2.0",
          "qos": 1
        },
        "kafka": {
          "bindingVersion": "0.3.0",
          "clientId": {
            "type": "string",
            "enum": [
              "my-app-id"
            ]
          }
        }
      }
    },
    "Unknown-PublishUserSignedUpDefaultBinding": {
      "action": "send",
      "channel": {
        "$ref": "#/channels/Unknown-UserSignedUpChannel"
      },
      "bindings": {
        "mqtt": {
          "qos": 1
        },
        "kafka": {
          "clientId": {
            "type": "string",
            "enum": [
              "my-app-id"
            ]
          }
        }
      }
    }
  },
  "components": {
    "messages": {
      "Unknown-UserSignedUp": {
        "payload": {
          "schemaFormat": "unknown-schema-format",
          "schema": {
            "type": "object",
            "properties": {
              "displayName": {
                "type": "string",
                "description": "Name of the user"
              },
              "email": {
                "type": "string",
                "format": "email",
                "description": "Email of the user"
              }
            },
            "externalDocs": {
              "url": "https://account-service/docs/UserSignedUp"
            },
            "deprecated": false
          }
        }
      },
      "Unknown-UserSignedUpV2": {
        "payload": {
          "$ref": "external-schema.json"
        }
      }
    }
  }
}

=== asyncapi/spec-json-schemas/test/docs/3.0.0/streetlights-json.json
{
  "asyncapi": "3.0.0",
  "info": {
    "title": "Account Service",
    "version": "1.0.0",
    "description": "This service is in charge of processing user signups"
  },
  "channels": {
    "Json-UserSignedUpChannel": {
      "address": "user/signedup",
      "messages": {
        "UserSignedUp": {
          "$ref": "#/components/messages/Json-UserSignedUp"
        }
      }
    }
  },
  "operations": {
    "Json-PublishUserSignedUp": {
      "action": "send",
      "channel": {
        "$ref": "#/channels/Json-UserSignedUpChannel"
      },
      "bindings": {
        "mqtt": {
          "bindingVersion": "0.2.0",
          "qos": 1
        },
        "kafka": {
          "bindingVersion": "0.3.0",
          "clientId": {
            "type": "string",
            "enum": [
              "my-app-id"
            ]
          }
        }
      }
    },
    "Json-PublishUserSignedUpDefaultBinding": {
      "action": "send",
      "channel": {
        "$ref": "#/channels/Json-UserSignedUpChannel"
      },
      "bindings": {
        "mqtt": {
          "qos": 1
        },
        "kafka": {
          "clientId": {
            "type": "string",
            "enum": [
              "my-app-id"
            ]
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Json-UserSignedUpHeaders": {
        "schemaFormat": "application/schema+json;version=draft-07",
        "schema": {
          "type": "object",
          "properties": {
            "applicationInstanceId": {
              "type": "string",
              "description": "Application instance Id"
            },
            "correlationId": {
              "type": "string",
              "description": "Correlation Id"
            }
          }
        }
      },
      "Json-ReferencedSchema" : {
        "schemaFormat": "application/schema+json;version=draft-07",
        "schema": {
          "$ref": "reference-to-some-json-schema-file.json"
        }
      }
    },
    "messages": {
      "Json-UserSignedUp": {
        "headers": {
          "$ref": "#/components/schemas/Json-UserSignedUpHeaders"
        },
        "payload": {
          "schemaFormat": "application/schema+json;version=draft-07",
          "schema": {
            "type": "object",
            "description": "This is a user record in a fictitious to-do-list management app. It supports arbitrary grouping and nesting of items, and allows you to add items by email or by tweeting.\n\nNote this app doesn't actually exist. The schema is just a demo for [Avrodoc](https://github.com/ept/avrodoc)!",
            "properties": {
              "id": {
                "type": "integer",
                "description": "System-assigned numeric user ID. Cannot be changed by the user."
              },
              "username": {
                "type": "string",
                "description": "The username chosen by the user. Can be changed by the user."
              },
              "passwordHash": {
                "type": "string",
                "description": "The user's password, hashed using [scrypt](http://www.tarsnap.com/scrypt.html)."
              },
              "signupDate": {
                "type": "number",
                "description": "Timestamp (milliseconds since epoch) when the user signed up"
              },
              "emailAddresses": {
                "type": "array",
                "description": "All email addresses on the user's account",
                "items": {
                  "type": "object",
                  "description": "Stores details about an email address that a user has associated with their account.",
                  "properties": {
                    "address": {
                      "type": "string",
                      "description": "The email address, e.g. `foo@example.com`"
                    },
                    "verified": {
                      "type": "boolean",
                      "description": "true if the user has clicked the link in a confirmation email to this address.",
                      "default": false
                    },
                    "dateAdded": {
                      "type": "number",
                      "description": "Timestamp (milliseconds since epoch) when the email address was added to the account."
                    },
                    "dateBounced": {
                      "type": "number",
                      "description": "Timestamp (milliseconds since epoch) when an email sent to this address last bounced. Reset to null when the address no longer bounces."
                    }
                  }
                }
              },
              "twitterAccounts": {
                "type": "array",
                "description": "All Twitter accounts that the user has OAuthed",
                "items": {
                  "type": "object",
                  "description": "Stores access credentials for one Twitter account, as granted to us by the user by OAuth.",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "Indicator of whether this authorization is currently active, or has been revoked",
                      "enum": [
                        "PENDING",
                        "ACTIVE",
                        "DENIED",
                        "EXPIRED",
                        "REVOKED"
                      ]
                    },
                    "userId": {
                      "type": "number",
                      "description": "Twitter's numeric ID for this user"
                    },
                    "screenName": {
                      "type": "string",
                      "description": "The twitter username for this account (can be changed by the user)"
                    },
                    "oauthToken": {
                      "type": "string",
                      "description": "The OAuth token for this Twitter account"
                    },
                    "oauthTokenSecret": {
                      "type": "string",
                      "description": "The OAuth secret, used for signing requests on behalf of this Twitter account. `null` whilst the OAuth flow is not yet complete."
                    },
                    "dateAuthorized": {
                      "type": "number",
                      "description": "Timestamp (milliseconds since epoch) when the user last authorized this Twitter account"
                    }
                  }
                }
              },
              "toDoItems": {
                "type": "array",
                "items": {
                  "type": "object",
                  "description": "A record is one node in a To-Do item tree (every record can contain nested sub-records).",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "User-selected state for this item (e.g. whether or not it is marked as done)",
                      "enum": [
                        "HIDDEN",
                        "ACTIONABLE",
                        "DONE",
                        "ARCHIVED",
                        "DELETED"
                      ]
                    },
                    "title": {
                      "type": "string",
                      "description": "One-line summary of the item"
                    },
                    "description": {
                      "type": "string",
                      "description": "Detailed description (may contain HTML markup)"
                    },
                    "snoozeDate": {
                      "type": "number",
                      "description": "Timestamp (milliseconds since epoch) at which the item should go from `HIDDEN` to `ACTIONABLE` status"
                    },
                    "subItems": {
                      "type": "array",
                      "doc": "List of children of this to-do tree node",
                      "items": {
                        "$ref": "#/components/messages/UserSignedUp/payload/schema/properties/toDoItems"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== asyncapi/spec-json-schemas/test/docs/3.0.0/streetlights-all.json
{
    "asyncapi": "3.0.0",
    "info": {
        "title": "Account Service",
        "version": "1.0.0",
        "description": "This service is in charge of processing user signups"
    },
    "channels": {
        "UserSignedUpChannel": {
            "address": "user/signedup/{test_param}",
            "parameters": {
                "test_param": {
                    "enum": [
                        "test"
                    ],
                    "default": "test",
                    "description": "Just a test description",
                    "examples": [
                        "test"
                    ],
                    "location": "$message.payload#",
                    "x-custom-extension": "test"
                }
            },
            "messages": {
                "UserSignedUp": {
                    "$ref": "#/components/messages/UserSignedUp"
                }
            }
        }
    },
    "operations": {
        "PublishUserSignedUp": {
            "action": "send",
            "channel": {
                "$ref": "#/channels/UserSignedUpChannel"
            },
            "bindings": {
                "mqtt": {
                    "bindingVersion": "0.2.0",
                    "qos": 1
                },
                "kafka": {
                    "bindingVersion": "0.3.0",
                    "clientId": {
                        "type": "string",
                        "enum": [
                            "my-app-id"
                        ]
                    }
                }
            }
        },
        "PublishUserSignedUpDefaultBinding": {
            "action": "send",
            "channel": {
                "$ref": "#/channels/UserSignedUpChannel"
            },
            "bindings": {
                "mqtt": {
                    "qos": 1
                },
                "kafka": {
                    "clientId": {
                        "type": "string",
                        "enum": [
                            "my-app-id"
                        ]
                    }
                }
            }
        }
    },
    "components": {
        "messages": {
            "UserSignedUp": {
                "payload": {
                    "type": "object",
                    "properties": {
                        "displayName": {
                            "type": "string",
                            "description": "Name of the user"
                        },
                        "email": {
                            "type": "string",
                            "format": "email",
                            "description": "Email of the user"
                        }
                    }
                }
            },
            "UserSignedUpV2": {
                "payload": {
                    "$ref": "external-schema.json"
                }
            }
        }
    }
}

=== asyncapi/spec-json-schemas/test/docs/3.0.0/streetlights-openapi.json
{
  "asyncapi": "3.0.0",
  "info": {
    "title": "Account Service",
    "version": "1.0.0",
    "description": "This service is in charge of processing user signups"
  },
  "channels": {
    "UserSignedUpChannel": {
      "address": "user/signedup",
      "messages": {
        "UserSignedUp": {
          "$ref": "#/components/messages/UserSignedUp"
        }
      }
    }
  },
  "operations": {
    "PublishUserSignedUp": {
      "action": "send",
      "channel": {
        "$ref": "#/channels/UserSignedUpChannel"
      },
      "bindings": {
        "mqtt": {
          "bindingVersion": "0.2.0",
          "qos": 1
        },
        "kafka": {
          "bindingVersion": "0.3.0",
          "clientId": {
            "type": "string",
            "enum": [
              "my-app-id"
            ]
          }
        }
      }
    },
    "PublishUserSignedUpDefaultBinding": {
      "action": "send",
      "channel": {
        "$ref": "#/channels/UserSignedUpChannel"
      },
      "bindings": {
        "mqtt": {
          "qos": 1
        },
        "kafka": {
          "clientId": {
            "type": "string",
            "enum": [
              "my-app-id"
            ]
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ReferencedSchema" : {
        "schemaFormat": "application/vnd.oai.openapi;version=3.0.0",
        "schema": {
          "$ref": "reference-to-some-openapi-file.json"
        }
      }
    },
    "messages": {
      "UserSignedUp": {
        "payload": {
          "schemaFormat": "application/vnd.oai.openapi;version=3.0.0",
          "schema": {
            "properties": {
              "id": {
                "type": "integer"
              },
              "name": {
                "type": "string"
              },
              "completed": {
                "type": "boolean"
              },
              "completed_at": {
                "type": "string",
                "format": "date-time",
                "nullable": true
              }
            },
            "required": [
              "id",
              "name",
              "completed"
            ]
          }
        }
      }
    }
  }
}
