=== asyncapi/spec-json-schemas/definitions/3.0.0/operation.json
{
  "type": "object",
  "additionalProperties": false,
  "patternProperties": {
    "^x-[\\w\\d\\.\\x2d_]+$": {
      "$ref": "http://asyncapi.com/definitions/3.0.0/specificationExtension.json"
    }
  },
  "required": [
    "action",
    "channel"
  ],
  "properties": {
    "action": {
      "type": "string",
      "description": "Allowed values are send and receive. Use send when it's expected that the application will send a message to the given channel, and receive when the application should expect receiving messages from the given channel.",
      "enum": ["send", "receive"]
    },
    "channel": {
      "$ref": "http://asyncapi.com/definitions/3.0.0/Reference.json"
    },
    "messages": {
      "type": "array",
      "items": {
        "$ref": "http://asyncapi.com/definitions/3.0.0/Reference.json"
      }
    },
    "reply": {
      "oneOf": [
        {
          "$ref": "http://asyncapi.com/definitions/3.0.0/Reference.json"
        },
        {
          "$ref": "http://asyncapi.com/definitions/3.0.0/operationReply.json"
        }
      ]
    },
    "traits": {
      "type": "array",
      "items": {
        "oneOf": [
          {
            "$ref": "http://asyncapi.com/definitions/3.0.0/Reference.json"
          },
          {
            "$ref": "http://asyncapi.com/definitions/3.0.0/operationTrait.json"
          }
        ]
      }
    },
    "title": {
      "type": "string",
      "description": "A human-friendly title for the operation."
    },
    "summary": {
      "type": "string",
      "description": "A brief summary of the operation."
    },
    "description": {
      "type": "string",
      "description": "A longer description of the operation. CommonMark is allowed."
    },
    "security": {
      "$ref": "http://asyncapi.com/definitions/3.0.0/securityRequirements.json"
    },
    "tags": {
      "type": "array",
      "items": {
        "oneOf": [
          {
            "$ref": "http://asyncapi.com/definitions/3.0.0/Reference.json"
          },
          {
            "$ref": "http://asyncapi.com/definitions/3.0.0/tag.json"
          }
        ]
      },
      "uniqueItems": true
    },
    "externalDocs": {
      "oneOf": [
        {
          "$ref": "http://asyncapi.com/definitions/3.0.0/Reference.json"
        },
        {
          "$ref": "http://asyncapi.com/definitions/3.0.0/externalDocs.json"
        }
      ]
    },
    "bindings": {
      "oneOf": [
        {
          "$ref": "http://asyncapi.com/definitions/3.0.0/Reference.json"
        },
        {
          "$ref": "http://asyncapi.com/definitions/3.0.0/operationBindingsObject.json"
        }
      ]
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://asyncapi.com/definitions/3.0.0/operation.json"
}

=== asyncapi/spec-json-schemas/examples/3.0.0/operation.json
[{
	"title": "User sign up",
	"summary": "Action to sign a user up.",
	"description": "A longer description",
	"channel": {
		"$ref": "#/channels/userSignup"
	},
	"action": "send",
	"security": [
		{
			"petstore_auth": ["write:pets", "read:pets"]
		}
	],
	"tags": [{ "name": "user" }, { "name": "signup" }, { "name": "register" }],
	"bindings": {
		"amqp": {
			"ack": false
		}
	},
	"traits": [{ "$ref": "#/components/operationTraits/kafka" }],
	"messages": [{ "$ref": "#/components/messages/userSignedUp" }],
	"reply": {
		"address": {
			"location": "$message.header#/replyTo"
		},
		"channel": {
			"$ref": "#/channels/userSignupReply"
		},
		"messages": [{ "$ref": "#/components/messages/userSignedUpReply" }]
	}
}]
